### ISSUE TITLE
Error running "go run main.go"

### ISSUE THREAD

**Issue by ayyar** [easyCZ/grpc-web-hacker-news#3]
I'm seeing this error when I tried to run the server:

# command-line-arguments
./main.go:20:47: cannot use grpcServer (type *"google.golang.org/grpc".Server) as type *"github.com/easyCZ/grpc-web-hacker-news/server/vendor/google.golang.org/grpc".Server in argument to grpc_web_hacker_news.RegisterHackerNewsServiceServer
./main.go:28:34: cannot use wrappedGrpc (type *"github.com/improbable-eng/grpc-web/go/grpcweb".WrappedGrpcServer) as type *"github.com/easyCZ/grpc-web-hacker-news/server/vendor/github.com/improbable-eng/grpc-web/go/grpcweb".WrappedGrpcServer in argument to "github.com/easyCZ/grpc-web-hacker-news/server/middleware".NewGrpcWebMiddleware

**Comment by betchi** [comment]
@ayyar 

It will work if you deploy this project under $GOPATH.

Like this.

```
mkdir -p $GOPATH/src/github.com/easyCZ
cd $GOPATH/src/github.com/easyCZ
git clone https://github.com/easyCZ/grpc-web-hacker-news.git
cd grpc-web-hacker-news/
./start.sh
```

**Comment by easyCZ** [comment]
I've now upgraded the project to use go-modules. See https://github.com/easyCZ/grpc-web-hacker-news/pull/15
