### ISSUE TITLE
"Response closed without headers" 

### ISSUE THREAD

**Issue by Vivek205** [easyCZ/grpc-web-hacker-news#7]
Only the heading appears on the page. List_stories api call is failing.
I just cloned and executed the start.sh file. @easyCZ

**Comment by easyCZ** [comment]
Hey, thanks for raising. I'll take a look later today.

**Comment by sanderpick** [comment]
This answer applies here too: https://github.com/easyCZ/grpc-web-hacker-news/issues/3#issuecomment-436857024

**Comment by easyCZ** [comment]
I've now upgraded the project to use go-modules. See https://github.com/easyCZ/grpc-web-hacker-news/pull/15 

This was due to incorrect CORS handling.
